# Generated by Django 4.2.2 on 2023-06-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swordsmith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job', models.CharField(choices=[('P', 'Polish'), ('S', 'Sharpen'), ('R', 'Remodel')], default='P', max_length=1)),
                ('sword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sword')),
            ],
        ),
    ]
